name: Integration tests

on:
  pull_request:
  push:
    branches:
      - dev/tests

jobs:
  smoke-action:
    name: Smoke test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2
      - name: Test local Action
        uses: ./
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          project: "@sourcecred"
          project-file: .github/github.json
          weights: .github/weights.json
          branch-against: master
          automated: true
          test-run: true
